cpl_data<-read.table( "household_power_consumption.txt",sep = ";",header = TRUE,na.strings = "?",colClasses = c("character","character","numeric"))
cpl_data$Date<-as.Date(cpl_data$Date,"%d/%m/%Y")
data<-cpl_data[cpl_data$Date =="2007-02-01"|cpl_data$Date =="2007-02-02", ]
data<-cbind(data,weekday=weekdays.Date(data$Date,abbreviate = TRUE))
data$datetime<- paste(data$Date,data$Time)
data$datetime<-as.POSIXct(data$datetime)
quartz()
par(mar=c(4,6,4,4))
plot(data$datetime,data$Sub_metering_1,type = "l",col="black",xlab="",ylab="energy sub metering")
points(data$datetime,data$Sub_metering_2,type = "l",col="red")
points(data$datetime,data$Sub_metering_3,type = "l",col="blue")
legend("topright",pch="-",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="plot3.png")
dev.off()