cpl_data<-read.table( "household_power_consumption.txt",sep = ";",header = TRUE,na.strings = "?",colClasses = c("character","character","numeric"))
cpl_data$Date<-as.Date(cpl_data$Date,"%d/%m/%Y")
data<-cpl_data[cpl_data$Date =="2007-02-01"|cpl_data$Date =="2007-02-02", ]
data<-cbind(data,weekday=weekdays.Date(data$Date,abbreviate = TRUE))
data$datetime<- paste(data$Date,data$Time)
data$datetime<-as.POSIXct(data$datetime)
quartz()
par(mfrow=c(2,2),mar=c(4,4,4,4))
plot(data$datetime,data$Global_active_power,type="l",ylab = "Global Active Power(kilowatts)",xlab = "")
plot(data$datetime,data$Voltage,type="l",ylab = "Voltage",xlab = "datetime")
plot(data$datetime,data$Sub_metering_1,type = "l",col="black",xlab="",ylab="energy sub metering")
points(data$datetime,data$Sub_metering_2,type = "l",col="red")
points(data$datetime,data$Sub_metering_3,type = "l",col="blue")
legend("topright",pch="-",col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(data$datetime,data$Global_reactive_power,type = "l",col="black",xlab="datetime",ylab="Global_reactive_power")
dev.copy(png,file="plot4.png")
dev.off()